# Generated by Django 4.0.4 on 2022-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_head', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='photos/blogs/')),
                ('blog_content', models.TextField()),
                ('blog_summary', models.TextField(max_length=355)),
                ('writer_content', models.CharField(max_length=5000)),
                ('writer_age', models.CharField(default=None, max_length=3)),
                ('writer_name', models.CharField(default=None, max_length=50)),
                ('writer_Image', models.ImageField(upload_to='photos/writers/')),
            ],
        ),
    ]
