# Generated by Django 4.0.4 on 2022-05-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writer_Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer_age',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer_name',
        ),
    ]
