# Generated by Django 4.0.4 on 2022-05-13 08:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
