# Generated by Django 4.0.4 on 2022-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_blog_content_alter_blog_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(default='This is a new blog post.', max_length=100),
        ),
    ]
