# Generated by Django 4.0.4 on 2022-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(max_length=100),
        ),
    ]
