# Generated by Django 4.0.4 on 2022-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users/avatars/'),
        ),
    ]
